apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo-container
        image: purushothamareddy/springdemo
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  selector:
    app: spring-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
